#!/usr/bin/env python3
"""Generate the smooth original cover used by the now-playing showcase fixture.

The full-bleed artwork is drawn at 512x512 with gradient light, blur, and soft
optical forms, then antialiased down to the 64x64 RGB565 image consumed by the
host render test. Writes
esphome/tests/render_test/components/pixoo64_render_test/showcase_cover.h.
Pass --check to verify the generated header without modifying it.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

SOURCE_SIZE = 512
COVER_SIZE = 64


def clamp_channel(value: float) -> int:
    return max(0, min(255, int(round(value))))


def build_source_artwork() -> Image.Image:
    """Draw bright original cover artwork without external material."""
    size = SOURCE_SIZE
    image = Image.new("RGB", (size, size))
    pixels = image.load()
    lights = (
        (0.08, 0.12, 0.48, 0.50, (0, 150, 105), 1.1),
        (0.88, 0.12, 0.50, 0.45, (120, 15, 115), 1.2),
        (0.20, 0.92, 0.55, 0.50, (205, 75, -25), 1.0),
        (0.85, 0.82, 0.55, 0.55, (185, -5, 45), 1.0),
        (0.52, 0.48, 0.40, 0.42, (110, 105, 40), 1.6),
    )
    for y in range(size):
        ny = y / (size - 1)
        for x in range(size):
            nx = x / (size - 1)
            red, green, blue = 28.0, 88.0, 125.0
            for center_x, center_y, width, height, color, weight in lights:
                intensity = math.exp(
                    -(
                        ((nx - center_x) / width) ** 2
                        + ((ny - center_y) / height) ** 2
                    )
                    * weight
                )
                red += color[0] * intensity
                green += color[1] * intensity
                blue += color[2] * intensity
            grain = (
                ((x * 92837111) ^ (y * 689287499) ^ (x * y * 283923481))
                & 255
            ) / 255.0 - 0.5
            pixels[x, y] = (
                clamp_channel(red + grain * 2.0),
                clamp_channel(green + grain * 1.5),
                clamp_channel(blue + grain * 2.0),
            )

    ribbons = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(ribbons)
    draw.arc(
        (-110, 70, 430, 610),
        205,
        330,
        fill=(255, 236, 178, 105),
        width=28,
    )
    draw.arc(
        (80, -170, 650, 400),
        85,
        245,
        fill=(176, 255, 244, 100),
        width=24,
    )
    draw.arc(
        (-50, -70, 560, 540),
        300,
        80,
        fill=(255, 155, 205, 80),
        width=18,
    )
    ribbons = ribbons.filter(ImageFilter.GaussianBlur(13))
    image = Image.alpha_composite(image.convert("RGBA"), ribbons)

    glass = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(glass)
    draw.ellipse(
        (150, 105, 420, 375),
        fill=(255, 245, 224, 30),
        outline=(255, 255, 245, 150),
        width=5,
    )
    draw.ellipse((190, 135, 385, 330), fill=(255, 180, 148, 35))
    glass = glass.filter(ImageFilter.GaussianBlur(5))
    return Image.alpha_composite(image, glass).convert("RGB")


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)


def generated_header() -> str:
    source = build_source_artwork()
    cover = source.resize((COVER_SIZE, COVER_SIZE), Image.Resampling.LANCZOS)
    pixels = [rgb565(*pixel) for pixel in cover.get_flattened_data()]
    lines = [
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace esphome::pixoo64_render_test::showcase_cover {",
        "",
        "// Original artwork rendered at 512x512, then antialiased to the",
        "// 64x64 RGB565 cover consumed by the now-playing render fixture.",
        "// Generated by tools/gen-showcase-cover.py.",
        f"constexpr int kWidth = {COVER_SIZE};",
        f"constexpr int kHeight = {COVER_SIZE};",
        "constexpr uint16_t kPixels[kWidth * kHeight] = {",
    ]
    for offset in range(0, len(pixels), 12):
        row = ", ".join(
            f"0x{value:04x}" for value in pixels[offset : offset + 12]
        )
        lines.append(f"    {row},")
    lines.extend(
        [
            "};",
            "",
            "}  // namespace esphome::pixoo64_render_test::showcase_cover",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="verify generated output is current"
    )
    args = parser.parse_args()
    repo = Path(__file__).resolve().parent.parent
    output = (
        repo
        / "esphome/tests/render_test/components/pixoo64_render_test/showcase_cover.h"
    )
    generated = generated_header()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"generated showcase cover is stale: {output}")
        print(f"up to date: {output}")
        return 0
    output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
