#!/usr/bin/env python3
"""Rasterize the split-flap watch face digits into a C++ coverage table.

Each digit is a set of stroke centerlines in a 16x22 cell. Coverage per pixel is
the area within half a stroke width of any centerline, sampled on a 4x4 grid, so
edges land on intermediate values instead of stair-stepping. Curves are polyline
approximations of ellipse arcs.

Writes esphome/components/pixoo64_content/dashboard/clock/split_flap_digits.h.
Run: .venv/bin/python tools/gen-split-flap-digits.py
Pass --check to verify output without modifying it.
"""
import argparse
import math
from pathlib import Path

W, H = 16, 22
STROKE = 2.8
SUBSAMPLES = 4

# Stroke centerline extents inside the cell.
L, R = 3.0, 13.0
T, B = 2.5, 19.5
CX = (L + R) / 2


def arc(cx, cy, rx, ry, a0, a1, steps=48):
    """Ellipse arc from a0 to a1 degrees; 0 = right, 90 = down."""
    pts = []
    for i in range(steps + 1):
        a = math.radians(a0 + (a1 - a0) * i / steps)
        pts.append((cx + rx * math.cos(a), cy + ry * math.sin(a)))
    return pts


def ellipse(cx, cy, rx, ry):
    return arc(cx, cy, rx, ry, 0, 360)


# Each digit is a list of polylines through the stroke centers.
DIGITS = {
    0: [ellipse(CX, 11.0, 5.0, 8.5)],
    1: [
        [(CX, T), (CX, B)],
        [(4.8, 5.6), (CX, T)],
        [(4.2, B), (11.8, B)],
    ],
    2: [
        arc(CX, 7.0, 5.0, 4.5, 160, 380),
        [(12.6, 8.6), (3.2, B)],
        [(3.0, B), (13.0, B)],
    ],
    3: [
        arc(CX, 6.8, 4.8, 4.3, 200, 450),
        arc(CX, 15.2, 5.0, 4.3, 270, 540),
    ],
    4: [
        [(10.5, T), (2.8, 14.0)],
        [(2.8, 14.0), (13.2, 14.0)],
        [(10.5, T), (10.5, B)],
    ],
    5: [
        [(12.8, T), (3.4, T)],
        [(3.4, T), (3.4, 9.3)],
        [(3.4, 9.3), (8.6, 8.9)],
        arc(CX, 14.2, 5.0, 5.3, -65, 165),
    ],
    6: [
        ellipse(CX, 14.7, 5.0, 4.8),
        arc(11.0, 14.0, 8.0, 11.0, -90, -180),
    ],
    7: [
        [(3.0, T), (13.0, T)],
        [(13.0, T), (6.0, B)],
    ],
    8: [
        ellipse(CX, 7.0, 4.6, 4.4),
        ellipse(CX, 15.0, 5.0, 4.6),
    ],
    9: [
        ellipse(CX, 7.3, 5.0, 4.8),
        arc(5.0, 8.0, 8.0, 11.5, 0, 90),
    ],
}


def segment_distance(px, py, ax, ay, bx, by):
    dx, dy = bx - ax, by - ay
    length_sq = dx * dx + dy * dy
    if length_sq == 0.0:
        return math.hypot(px - ax, py - ay)
    t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / length_sq))
    return math.hypot(px - (ax + t * dx), py - (ay + t * dy))


def inside(px, py, polylines):
    half = STROKE / 2
    for pts in polylines:
        for i in range(len(pts) - 1):
            ax, ay = pts[i]
            bx, by = pts[i + 1]
            if segment_distance(px, py, ax, ay, bx, by) <= half:
                return True
    return False


def coverage(digit):
    polylines = DIGITS[digit]
    rows = []
    for y in range(H):
        row = []
        for x in range(W):
            hits = 0
            for sy in range(SUBSAMPLES):
                for sx in range(SUBSAMPLES):
                    px = x + (sx + 0.5) / SUBSAMPLES
                    py = y + (sy + 0.5) / SUBSAMPLES
                    if inside(px, py, polylines):
                        hits += 1
            row.append(round(255 * hits / (SUBSAMPLES * SUBSAMPLES)))
        rows.append(row)
    return rows


def generated_header() -> str:
    lines = [
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace esphome::pixoo64::clockface {",
        "",
        "// Per-pixel coverage of each digit, 0 = card, 255 = full digit ink.",
        "// Intermediate values anti-alias the edges. Generated by",
        "// tools/gen-split-flap-digits.py; edit the stroke geometry there.",
        f"constexpr int kDigitW = {W};",
        f"constexpr int kDigitH = {H};",
        "",
        f"constexpr uint8_t kDigitCoverage[10][kDigitH][kDigitW] = {{",
    ]
    for digit in range(10):
        lines.append(f"    // {digit}")
        lines.append("    {")
        for row in coverage(digit):
            cells = ", ".join(f"{v:3d}" for v in row)
            lines.append(f"        {{{cells}}},")
        lines.append("    },")
    lines += ["};", "", "}  // namespace esphome::pixoo64::clockface", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated output is current")
    args = parser.parse_args()
    repo = Path(__file__).resolve().parent.parent
    output = repo / "esphome/components/pixoo64_content/dashboard/clock/split_flap_digits.h"
    generated = generated_header()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"generated split-flap digits are stale: {output}")
        print(f"up to date: {output}")
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
