# Fallback AP password.
fallback_ap_password: pixoo64-ap
# ESPHome API encryption key.
api_encryption_key: JzOaEpFCY6Po4c+hZTGwg1fg16kwoY1MjOEV+AULsa8=
# ESPHome OTA password.
ota_password: pixoo64-ota
